# Site settings
name: Huey Yun Teo
email: nico.thyun@gmail.com
url: "http://nicothyun.github.io" # the base hostname & protocol for your site
description: Hi I am HY and I'm a marketer
title: "Huey Yun Teo, Marketing & Design"
baseurl: /nicothyun

gems:
  - octopress-autoprefixer

# Social
twitter: nicothyun
instagram: nicothyun
github: nicothyun

# Build settings
markdown: kramdown

# Serving
port: 4000
host: 0.0.0.0

permalink: pretty

sass:
    style: :compressed

exclude: [vendor]
