# Site settings
name: Fivos Avgerinos
email: afivos@me.com
url: "http://afivos.com" # the base hostname & protocol for your site
description: > # this means to ignore newlines until "baseurl:"
  Fivos Avgerinos is a multidisciplinary designer interested in speculative work related to the human, culture, and material.
title: "Fivos Avgerinos"
baseurl: "" # the subpath of your site, e.g. /blog/

gems:
  - octopress-autoprefixer

# Social
twitter: afivos
dribbble: afivos
instagram: afivos
github: afivos

# Build settings
markdown: kramdown

# Serving
port: 4000
host: 0.0.0.0

permalink: pretty

sass:
    style: :compressed